# @Author: juan
# @Date:   2019-01-08T11:12:37+09:00
# @Last modified by:   juan
# @Last modified time: 2019-01-08T12:04:05+09:00

name: template
dependencies:
  - python==3.6.0
  - jupyter
  - scipy==1.1.0
  - pandas==0.23.4
  - matplotlib
  - seaborn==0.9.0
  - scikit-learn==0.20.0
  - statsmodels==0.9.0
  - click
  - pip:
    - pytest
    - xgboost==0.80
    #- Flask
